name: binit
description: "Graduation Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  intl: ^0.20.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  flutter_local_notifications: ^17.2.0
  firebase_database: ^10.5.7
  flutter_secure_storage: ^9.0.0
  firebase_messaging: ^14.7.8

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^25.3.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
  assets:
    - assets/logo/logo.png
    - assets/png/leftcornergreen.png
    - assets/png/rightcornergreen.png
    - assets/png/bottomright.png
    - assets/png/bin1.png
    - assets/png/bin2.png
    - assets/png/bin3.png
    - assets/png/profile.png
    - assets/png/SellDone.png
    - assets/png/waiting.png
